use_frameworks!

target 'QCloudUploaderUtils_Example' do
  pod 'QCloudUploaderUtils', :path => '../'

  target 'QCloudUploaderUtils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
